### PR TITLE
Fix typing declerations

### PR DESCRIPTION
**Pull request by niekschoemaker**
#### Information

> Check one

- [ ] This includes major changes (new features, version required)
- [ ] This includes minor changes (doesn't change usage)
- [x] This includes patches (bug fixes, documentation changes etc)

#### Is this related to an issue?
None on git.

The imports in the typing file (index.d.ts) would break when using the dependency with typescript, since it references ../src/types directly, while the src folder doesn't exist anymore but is changed to dist.

#### Changes made

The tsconfig has been changed to automatically emit type declerations and the edits to the Logger class has been moved to the Logger.ts itself using declare "." and an interface.

#### Confirmations

> Check all that apply

- [ ] This uses consistent code style
- [x] This is tested and works

I tested this locally, and this fixes the issues I had with typescript builds and the typing works as expected (Logger instance has the debug, error, etc on the instance according to typescript)

### CODE REVIEW

**Comment by niekschoemaker** [comment]
I've been struggling with this for a bit, since I didn't know what the best solution would be to fix this issue (tsc doesn't fix imports automatically) so this solution seems to allow for the best of both worlds, and just ahve typescript declare all types with the builtin type emitter, and just extend the class manually.
This also removes the need to declare the entire class, and only the dynamically added properties have to be declared manually.

**Comment by eartharoid** [comment]
Thanks @niekschoemaker (sorry I didn't notice it earlier).

Do you know if it is possible for types to work with the configurable log levels and namespaces, or how the user would overwrite the default types?

**Comment by niekschoemaker** [comment]
> Thanks @niekschoemaker (sorry I didn't notice it earlier).
> 
> Do you know if it is possible for types to work with the configurable log levels and namespaces, or how the user would overwrite the default types?

I'll have a look.

I might also be able to get it working with the provided config, but I'm not sure if that can work in Typescript, maybe.

But for overriding the default typings something like this should definitely work:
```ts
declare module "leekslazylogger" {
    interface Logger {
        other(...content: LogContent): void;
        another(...content: LogContent): void;
    }
}
```

That would add other and another to the logging levels, but as for defining it for the config, that's going to take some Typescript trickery, but I'll have a look see if I can get that working.

**Comment by niekschoemaker** [comment]
> > Thanks @niekschoemaker (sorry I didn't notice it earlier).
> > Do you know if it is possible for types to work with the configurable log levels and namespaces, or how the user would overwrite the default types?
> 
> I'll have a look.
> 
> I might also be able to get it working with the provided config, but I'm not sure if that can work in Typescript, maybe.
> 
> But for overriding the default typings something like this should definitely work:
> 
> ```ts
> declare module "leekslazylogger" {
>     interface Logger {
>         other(...content: LogContent): void;
>         another(...content: LogContent): void;
>     }
> }
> ```
> 
> That would add other and another to the logging levels, but as for defining it for the config, that's going to take some Typescript trickery, but I'll have a look see if I can get that working.

I've been banging my head against trying to get it to work dynamically but I have no idea how I would get that to work, it might be possible but I can't figure out how, so I think just letting people use the declare module way of doing it would make more sense.

Unless somebody could come up with the way of doing it.

**Comment by eartharoid** [comment]
Ok, thanks.

**Comment by eartharoid** [comment]
Published in version 5.0.1

**Pull request merged**
